### ISSUE TITLE
terraform.EvalValidateResource, err: Warnings: []. Errors: [connection is shut down]

### ISSUE THREAD

**Issue by conrado** [terraform-providers/terraform-provider-cloudflare#17] opened 2017-08-08 22:15 UTC
Hi there,

### Terraform Version

Terraform v0.10.0
provider.cloudflare: version = "~> 0.1"

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record

### Terraform Configuration Files
```hcl
variable "CLOUDFLARE_EMAIL" {}
variable "CLOUDFLARE_TOKEN" {}
variable "domain" {
  default = "secretsauce.com"
}

provider "cloudflare" {
  email = "${var.CLOUDFLARE_EMAIL}" 
  token = "${var.CLOUDFLARE_TOKEN}"
}

...

resource "cloudflare_record" "welcome_TXT" {
  domain  = "${var.domain}"
  name    = "welcome"
  value   = "google-site-verification=snipped"
  type    = "TXT"
}

resource "cloudflare_record" "welcome_TXT_1" {
  domain  = "${var.domain}"
  name    = "welcome"
  value   = "v=spf1 include:welcome.secretsauce.com._nspf.vali.email include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all"
  type    = "TXT"
}
```
and a few hundred other records. I have exported our ~350 DNS records, that we previously created manually on cloudflare. Now I have used a template engine to render `cloudflare_record` configuration for terraform.

I would be happy to provide the full configuration files in a non-public way if you would like to reproduce the error.

### Debug Output
I cannot provide the debug output publicly as it contains sensitive data

### Panic Output
I cannot provide the panic output publicly as it contains sensitive data

### Expected Behavior
What should have happened?

### Actual Behavior
Terraform should have formulated a plan, hopefully that no action was required.

### Steps to Reproduce
`terraform plan`

### References
- terraform/terraform#8341

**Comment by radeksimko** [comment] 2017-08-09 07:03
Hi @conrado 
I'm struggling to find/understand the question or description of the problem. Did you receive any particular error or unexpected `plan` output?

> I would be happy to provide the full configuration files in a non-public way if you would like to reproduce the error.

Feel free to use our PGP key to encrypt configuration files (and debug logs, if possible) via https://keybase.io/hashicorp and send them to radek@hashicorp.com

Thanks.

**Comment by radeksimko** [comment] 2017-08-14 09:58
Hi @conrado 
thank you for providing all the details.

Here's the relevant part of the crash log with sensitive data redacted:

```
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: panic: Error reading level config: strconv.ParseBool: parsing "5": invalid syntax
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: goroutine 391 [running]:
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4201d1b90, 0xc4204a6740, 0x1, 0x1, 0xc4204a6712, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x311
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc4201d1b90, 0x16cafc8, 0x7, 0x1001201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:451 +0x135
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc4201d1b90, 0x16cafc8, 0x7, 0x100e9b2, 0xc420465290, 0x30, 0x30, 0x16992c0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:428 +0x61
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc420431770, 0x16cafc8, 0x7, 0xc420289680, 0xc4201fb618, 0xc4201d1b90, 0x0, 0x0, 0x0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1051 +0xb5
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc420431770, 0x16cafc8, 0x7, 0xc420289680, 0xc420451020, 0xc4201d1b90, 0x0, 0x0, 0x0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:685 +0x43b
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420431770, 0xc42010a8c0, 0xc420464f60, 0x0, 0x0, 0x10105c2)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:389 +0x1c2
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc42041bb60, 0xc42010a8c0, 0xc420464f60, 0x11, 0xc420290498, 0x1)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:211 +0x15b
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc42019ce70, 0xc42010a870, 0xc42010a8c0, 0xc420464f60, 0x1bd6960, 0x0, 0x0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:255 +0x84
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc42043b0e0, 0xc420450f40, 0xc4204a6360, 0x0, 0x0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:499 +0x57
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: reflect.Value.call(0xc4201d4b40, 0xc42000d200, 0x13, 0x16c7abc, 0x4, 0xc420045f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: reflect.Value.Call(0xc4201d4b40, 0xc42000d200, 0x13, 0xc42002cf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: net/rpc.(*service).call(0xc420471a40, 0xc420471a00, 0xc420476898, 0xc420321080, 0xc42043b160, 0x15b8da0, 0xc420450f40, 0x16, 0x15b8de0, 0xc4204a6360, ...)
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: created by net/rpc.(*Server).ServeCodec
2017/08/09 13:20:36 [DEBUG] plugin: terraform-provider-cloudflare_v0.1.0_x4: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2017/08/09 13:20:36 [DEBUG] plugin: /*REDACTED*/.terraform/plugins/darwin_amd64/terraform-provider-cloudflare_v0.1.0_x4: plugin process exited
```

I believe this is a duplicate of core schema issue tracked in https://github.com/hashicorp/terraform/issues/9488 therefore I will close this one.

Do let me know if you disagree and we can re-open.

**Closed by radeksimko** 2017-08-14 09:58 UTC
Labels: bug, crash

**Comment by conrado** [comment] 2017-08-14 23:52
Thank you for your help Radek
