### ISSUE TITLE
cloudflare_record changes while no values have changed

### ISSUE THREAD

**Issue by shiftie** [terraform-providers/terraform-provider-cloudflare#375] opened 2019-06-12 09:14 UTC
Hi!

When `cloudflare_record` is configured with a `value` attribute which value is ending with `.` like: `_some.string.acm-validations.aws.` (that kind of values are returned by `aws_acm_certificate` for instance), it seems that `cloudflare_record` stores that value **without** the trailing `.` in the state. So the next time we run apply, it wants to update the record with the trailing `.` which is stored without it in the state again and so on....

### Terraform Version
0.12.1 (but it also happened with 0.11)

### Affected Resource(s)
`cloudflare_record`

### Expected Behavior
What should have happened?
If `value` attribute value doesn't change, the ressource shouldn't try to update.

### Actual Behavior
Ressource always wants to update.

### Steps to Reproduce
```hcl
resource "cloudflare_record" "foobar" {
  domain = "mydomain.com"
  name   = "terraform.mydomain.com."
  value  = "_some.string.acm-validations.aws."
  type   = "CNAME"
  ttl    = 3600
}
```

Then `terraform apply` will try to update the ressource  every time.

Thank you :)

**Comment by jacobbednarz** [comment] 2019-06-12 09:44
Thanks for the report!

This is a duplicate of https://github.com/terraform-providers/terraform-provider-cloudflare/issues/184 and I’ve expanded upon the reasoning a bit in 
https://github.com/terraform-providers/terraform-provider-cloudflare/issues/154

Do let me know if you have any thoughts though!

**Closed by jacobbednarz** 2019-06-12 09:44 UTC

**Comment by shiftie** [comment] 2019-06-12 12:59
Oh, ok I've used the replace trick. Thx.
