### ISSUE TITLE
Importing cloudflare_filter results in Error: nil entry in ImportState

### ISSUE THREAD

**Issue by grogancolin** [terraform-providers/terraform-provider-cloudflare#695] opened 2020-05-27 14:05 UTC
Hi there,

# ## Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
- cloudflare_filter

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
It's not particularly relevant here, but it's basically:
```hcl
resource "cloudflare_filter" "filter_name" {}
resource "cloudflare_firewall_rule" "rule_name" {
```

### Debug Output
https://gist.github.com/grogancolin/465367b3be7cc0a7d7a72f4c9c6c0aaa

### Expected Behavior
Import should've worked

### Actual Behavior
Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import cloudflare_filter.<resource_id> <zone_id>/<filter_id>`

### Important Factoids
We're an enterprise account in Cloudflare. Maybe there's some closed API or fields that aren't supported?

**Comment by jacobbednarz** [comment] 2020-05-27 21:03
From the looks of your logs, you're not importing anything.

```
2020-05-27T14:55:35.156+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.5.1_x4: 2020/05/27 14:55:35 [DEBUG] filter: cloudflare.Filter{ID:"", Expression:"", Paused:false, Description:"", Ref:""}
2020-05-27T14:55:35.156+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.5.1_x4: 2020/05/27 14:55:35 [DEBUG] filter error: error from makeRequest: HTTP status 404: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 10001,\n      \"message\": \"filters.api.not_found\"\n    }\n  ],\n  \"messages\": []\n}\n"
2020-05-27T14:55:35.156+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.5.1_x4: 2020/05/27 14:55:35 [INFO] Filter 6a1d1714a05f4e9082c56f610ba3b9dc no longer exists
```

**Comment by jacobbednarz** [comment] 2020-05-27 21:18
Given the following API responses:

```
$ curl -sH "X-Auth-Email: $CF_EMAIL" \
  -H "X-Auth-Key: $CF_API_KEY" \
  https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/firewall/rules | jq .

{
  "result": [
    {
      "id": "d4b980bedd7c445987248a0af0060a4f",
      "paused": false,
      "description": "test rule",
      "action": "log",
      "filter": {
        "id": "59489f7e430b4f18b1aa14846e1f67a7",
        "expression": "(ip.src eq 127.0.0.1)",
        "paused": false
      },
      "created_on": "2020-05-27T21:05:03Z",
      "modified_on": "2020-05-27T21:05:03Z"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 25,
    "count": 1,
    "total_count": 1,
    "total_pages": 1
  }
}
```

```
$ curl -sH "X-Auth-Email: $CF_EMAIL" \
  -H "X-Auth-Key: $CF_API_KEY" \
  https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/filters | jq

{
  "result": [
    {
      "id": "59489f7e430b4f18b1aa14846e1f67a7",
      "paused": false,
      "expression": "(ip.src eq 127.0.0.1)"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 25,
    "count": 1,
    "total_count": 1,
    "total_pages": 1
  }
}
```

With terraform configuration:

```hcl
variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "zone_id" {}

provider "cloudflare" {
  version = "~> 2.0"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

resource "cloudflare_filter" "example_filter" {
  zone_id     = var.zone_id
  description = "test filter"
  expression  = "(ip.src eq 127.0.0.1)"
}
```

And finally, importing and confirming the state.

```
$ terraform init && terraform import -var "cloudflare_email=$CF_EMAIL" -var "cloudflare_api_key=$CF_API_KEY" -var "zone_id=$CF_ZONE_ID" cloudflare_filter.example_filter 0da42c8d2132a9ddaf714f9e7c920711/59489f7e430b4f18b1aa14846e1f67a7

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
cloudflare_filter.example_filter: Importing from ID "0da42c8d2132a9ddaf714f9e7c920711/59489f7e430b4f18b1aa14846e1f67a7"...
cloudflare_filter.example_filter: Import prepared!
  Prepared cloudflare_filter for import
cloudflare_filter.example_filter: Refreshing state... [id=59489f7e430b4f18b1aa14846e1f67a7]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```
$ terraform state show cloudflare_filter.example_filter
# cloudflare_filter.example_filter:
resource "cloudflare_filter" "example_filter" {
    expression = "(ip.src eq 127.0.0.1)"
    id         = "59489f7e430b4f18b1aa14846e1f67a7"
    paused     = false
    zone_id    = "0da42c8d2132a9ddaf714f9e7c920711"
}
```

Closing this off as the `Import` is functioning correctly and the issue is that the IDs being referenced don't exist, hence failure to import.

**Closed by jacobbednarz** 2020-05-27 21:18 UTC

**Comment by grogancolin** [comment] 2020-06-05 13:13
Thanks @jacobbednarz . 

You're right, I was using the wrong ID.
It would be nice to have a better error message here though. 

```
Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.```

This makes you think it's not a problem with my config, but a problem with either the API or the provider.

**Comment by jacobbednarz** [comment] 2020-06-08 22:23
I don't think there is much we could change here (without creating other issues) as the cause is not finding the ID from the API while trying to sync the state, which is also a valid condition within the [`Read`](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/a522de34d92a728d938f63a4c1388a1c728b032f/cloudflare/resource_cloudflare_filter.go#L97) when the resource has been deleted from the remote source.

My advice would be when hitting these errors, to re-run with `TF_LOG=DEBUG` as there are some additional log entries provided that might lead you to diagnosing the issue.
