### ISSUE TITLE
cloud_access_rule ip firewall not appearing in cloudflare dashboard 

### ISSUE THREAD

**Issue by allan-simon** [terraform-providers/terraform-provider-cloudflare#290] opened 2019-04-13 22:38 UTC
I'm using 

Terraform v0.11.13
+ provider.cloudflare v1.12.0

I have the following  access_rule.tf

```
resource "cloudflare_access_rule" "7078a095e3ec926cb2489e52c7a62b7e" {
  notes = "Gandi (DNS)"
  mode  = "whitelist"

  configuration {
    target = "ip"
    value  = "217.70.184.38"
  }
}
```

this rule was created with `cf-terraforming` tool  (i.e the rule was existing before I terraformed it) 

interesting things is that at first i was not able to `terraform import` it. so I deleted it in cloudflare in order to recreate it. `terraform apply` did say it added stuff, but I saw nothing 
I decided to make a change in the `notes` , to re-apply, terraform told it was going to modify something, but still not result in the cloudflare dashboard 

So i'm a bit clueless on what's happening....

**Comment by jacobbednarz** [comment] 2019-04-15 03:46
I tried reproducing with the following setup.

```hcl
provider "cloudflare" {
  email  = "${var.cloudflare_email}"
  token  = "${var.cloudflare_token}"
  org_id = "${var.account_id}"
}

resource "cloudflare_access_rule" "example" {
  notes = "Gandi (DNS)"
  mode  = "whitelist"

  configuration {
    target = "ip"
    value  = "217.70.184.38"
  }
}
```

And this works as expected.

![](https://shares.jacobbednarz.com/scr69-eigph-bfo4p.png)

Looking at your setup, I do have a couple of notes:

- You can't use the identifier `7078a095e3ec926cb2489e52c7a62b7e` as the resource name. The provider will throw an exception the name must start with a letter and may contain only letters, digits,
underscores, and dashes.
- It might not matter here but are you intending on applying it account wide? Or just to the zone? Under the covers it does use different endpoints however it will default to the account if you don't define anything. To use a zone, try adding the `zone_id` into your resource.

Failing getting any further with this, please run the apply with `TF_LOG=DEBUG` prefixed. This will be noisy but will show the HTTP interactions and might point you towards the reason why these aren't getting updated in the console.

**Comment by allanlegalstart** [comment] 2019-04-15 20:35
it was account wide, I will try to re-do it , but unfortunately today as we were code-reviewing our huge integration of cloudflare in our terraform, we deleted a lot of unused/legacy rules, and it was part of them. I will try to re-add them in order to provide more information on this issue.

**Comment by jacobbednarz** [comment] 2019-04-15 20:48
Ok, no problems. I’ll close this off for now as it appears to work as designed but do ping me if you have more details and we can dig deeper.

**Closed by jacobbednarz** 2019-04-15 20:48 UTC
