### ISSUE TITLE
PageRule priority not honored

### ISSUE THREAD

**Issue by mbrowne** [terraform-providers/terraform-provider-cloudflare#187] opened 2019-01-02 18:22 UTC
I'm not sure if this is an issue with this provider or with the Cloudflare API itself...

### Terraform Version
0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_page_rule

### Terraform Configuration Files
```hcl
variable "zone" {}

resource "cloudflare_page_rule" "3" {
  priority = 3
  zone     = "${var.zone}"
  target   = "*${var.zone}/3/*"
  status   = "active"

  actions = {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "2" {
  priority = 2
  zone     = "${var.zone}"
  target   = "*${var.zone}/2/*"
  status   = "active"

  actions = {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "1" {
  priority = 1
  zone     = "${var.zone}"
  target   = "*${var.zone}/1/*"
  status   = "active"

  actions = {
    cache_level = "cache_everything"
  }
}
```

### Debug Output
https://gist.github.com/mbrowne/77057416f35854ba5dfb647d68d5cdfb

### Expected Behavior
Page rules created with priority values matching the config

### Actual Behavior
Priorities out of order. Raw JSON result from Cloudflare API showing state after running `terraform apply`:

```json
[
  {
    "id": "2ae3824bfd411d9a4f47d66aa86be72f",
    "targets": [
      {
        "target": "url",
        "constraint": {
          "operator": "matches",
          "value": "*matthewhbrowne.com/2/*"
        }
      }
    ],
    "actions": [{ "id": "cache_level", "value": "cache_everything" }],
    "priority": 3,
    "status": "active",
    "modified_on": "2019-01-02T18:16:22Z",
    "created_on": "2019-01-02T17:19:26Z"
  },
  {
    "id": "cb89c29a3a3e87c2599b4d996943e995",
    "targets": [
      {
        "target": "url",
        "constraint": {
          "operator": "matches",
          "value": "*matthewhbrowne.com/3/*"
        }
      }
    ],
    "actions": [{ "id": "cache_level", "value": "cache_everything" }],
    "priority": 2,
    "status": "active",
    "modified_on": "2019-01-02T18:16:21Z",
    "created_on": "2019-01-02T17:03:03Z"
  },
  {
    "id": "f0048a5e8175abd9e069e7a514574056",
    "targets": [
      {
        "target": "url",
        "constraint": {
          "operator": "matches",
          "value": "*matthewhbrowne.com/1/*"
        }
      }
    ],
    "actions": [{ "id": "cache_level", "value": "cache_everything" }],
    "priority": 1,
    "status": "active",
    "modified_on": "2019-01-02T18:16:22Z",
    "created_on": "2019-01-02T17:03:03Z"
  }
]
```

### Steps to Reproduce
Easiest way to reproduce:

1. `terraform apply`
1. `terraform destroy`
1. `terraform apply`

It might be necessary to run destroy and apply one more time before the issue shows up.

### Important Factoids
I created a brand new Cloudflare account to test this to verify the issue

**Comment by jacobbednarz** [comment] 2019-01-02 21:16
Thanks for reporting this @mbrowne!

If I understand your issue correctly, this is a known incompatibility where there are conflicting ordering processes between the Terraform provider and Cloudflare API. I know we have raised this with our Cloudflare folks but for posterity, I'll post a summary of it here.

The main issue here is that Terraform uses a declarative load order for resources and doesn't apply any control flow _unless_ one of the following conditions are required:

- A variable is referenced in a resource
- A `depends_on` attribute is defined within a resource

In contrast the Cloudflare API will reorder the page rules as they come in to ensure that they are sequential and there aren't gaps. For example, if you send in a rule with a `priority` of 3 yet don't have enough rules, it will become rule 1.

The way we've worked around this internally is by using a combination of the two, `depends_on` (for Terraform) and `priority` to meet the Cloudflare API requirements. Using your example above, this is how we have solved it.

(diff)

```diff
@@ -5,6 +5,7 @@
   zone     = "${var.zone}"
   target   = "*${var.zone}/3/*"
   status   = "active"
+  depends_on = ["cloudflare_page_rule.2"]

   actions = {
     cache_level = "cache_everything"
@@ -16,6 +17,7 @@
   zone     = "${var.zone}"
   target   = "*${var.zone}/2/*"
   status   = "active"
+  depends_on = ["cloudflare_page_rule.1"]

   actions = {
     cache_level = "cache_everything"
```

(full)

```hcl
variable "zone" {}

resource "cloudflare_page_rule" "3" {
  priority   = 3
  zone       = "${var.zone}"
  target     = "*${var.zone}/3/*"
  status     = "active"
  depends_on = ["cloudflare_page_rule.2"]

  actions = {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "2" {
  priority   = 2
  zone       = "${var.zone}"
  target     = "*${var.zone}/2/*"
  status     = "active"
  depends_on = ["cloudflare_page_rule.1"]

  actions = {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "1" {
  priority = 1
  zone     = "${var.zone}"
  target   = "*${var.zone}/1/*"
  status   = "active"

  actions = {
    cache_level = "cache_everything"
  }
}
```

This ensures that Terraform evaluates these resources in the order we want _and_ Cloudflare's priority stays correct and doesn't flap as mentioned in #65.

I know this is something that is being looked at from Cloudflare's side and I don't think the workaround in the provider would be manageable if implemented due to the additional overhead on every operation as you'd need to fetch all resources and re-evaluate everytime a change was initiated.

**Comment by mbrowne** [comment] 2019-01-04 15:43
Thanks very much for suggesting this workaround. The first time I tried it on our real Cloudflare account, the ordering of the rules still didn't match the order in our Terraform file, but then I removed all the rules and recreated them and it seems to be working fine now (I did it twice to be sure). If this workaround will continue to be necessary for a long time, perhaps it should be mentioned in the documentation? It wouldn't be a big deal if different orderings had the same effect, but different priority order can actually cause rules to be applied differently...

**Comment by mbrowne** [comment] 2019-01-07 22:02
Thanks. I actually already ran `terraform import` for each page rule (via a script I wrote, since it would be tedious to do it manually for all 20 of our page rules), so I'm not sure what was going on. But of course things will be much easier once we're fully migrated to Terraform.

**Comment by m1kola** [comment] 2019-02-08 14:01
Thanks for sharing the workaround. Is there a way to do something similar with modules? I have several modules which define page rules and I use some of them multiple times in my project. Modules are not 3rd party, so I can modify them.

**Comment by jacobbednarz** [comment] 2019-02-10 22:02
I don't think it would be possible to use a workaround like this and use modules as the ordering isn't reusable. Happy to be proved wrong here but I can't see a way where that would work and get any benefit from the modules.

**Comment by mbrowne** [comment] 2019-02-10 22:40
Well you could create a separate module for each page rule and pass in the priority number as a parameter. And rather than trying to automate the whole thing you could write a test to just verify that the human-entered numbers were entered correctly in sequential order. That's what I ended up doing for validation...wrote the test script in Go since it has the official HCL library (just the raw config values...it doesn't do variable interpolation like Terraform does internally, but that's irrelevant in the case of hard-coded priority numbers).

**Comment by jacobbednarz** [comment] 2019-02-10 22:45
@mbrowne I think the issue would still be present as you need the priority and the `depends_on` meta attribute which requires context of what should be applied. At that point, modules seem pretty redundant as you would be rewriting most of it when you reference it.

**Comment by m1kola** [comment] 2019-02-11 12:04
Thanks for your answers. Because of my time constrains, I ended up with a quite fragile solution which basically ignores `priority`. It "solves" the issue from https://github.com/terraform-providers/terraform-provider-cloudflare/issues/65 and allows me to set priority directly in Cloudflare. After setting the correct priority manually in Cloudflare I can modify page rules without modifying `priority` via terraform.

I added `lifecycle` with `ignore_changes` to my every rule:

```terraform
resource "cloudflare_page_rule" "name" {
  # ...

  lifecycle {
    # Ignore priority. We can't modify it via Terraform, at the moment,
    # so priority should be set in Cloudflare manually.
    # Ref: https://github.com/terraform-providers/terraform-provider-cloudflare/issues/187
    ignore_changes = "priority"
  }
}
```

It kinda works for me because I only manage 3 zones and I'm not going to change page rules often, but I do not recommend this workaround. if Cloudflare decide to change the way they handle priority in API requests like this, you will highly likely have your page rules silently broken (it's not documented anywhere, so It seems to be safe to assume that backward compatibility is not guaranteed).

**Comment by inge4pres** [comment] 2019-11-02 14:50
hey there @mbrowne, not sure if this can help but we solved the issue by using a configuration like this

```terraform
variable "pagerule_targets" {
  type = "map"
  default = {
    // special URIs
    "822" = "test.domain.com/ui/index.html"
    "821" = "test.domain.com/ui/"

    // wildcard paths
    "73" = "cms.domain.com/*html"
    "72" = "cms.domain.com/etc/*"

    // defaults
    "12" = "test.domain.com/*"
    "11" = "cms.domain.com/*"
  }

  
variable "pagerule_actions" {
  type = "map"
  default = {
    // special URIs
    "822" = {
      always_use_https = "true"
      cache_level = "cache_everything"
      edge_cache_ttl = "10"
    }
    "821" = {
      always_use_https = "true"
      cache_level = "cache_everything"
      edge_cache_ttl = "10"
    }
    // wildcard paths
    "73" = {
      cache_level = "cache_everything"
      edge_cache_ttl = "7200"
    }
    "72" = {
      cache_level = "cache_everything"
      edge_cache_ttl = "2419200"
    // defaults
    "12" = {
      always_use_https = "true"
      cache_level = "cache_everything"
      edge_cache_ttl = "86400"
    }
    "11" = {
      always_use_https = "true"
      cache_level = "cache_everything"
      edge_cache_ttl = "86400"
    }
  }


resource "cloudflare_page_rule" "rules" {
   count = "${length(keys(var.pagerule_targets))}"
   lifecycle {
    create_before_destroy = true
  }

  zone_id = "${cloudflare_zone.zone.id}"
  target = "${var.pagerule_targets[element(keys(var.pagerule_targets),count.index)]}"
  actions = "${list(var.pagerule_actions[element(keys(var.pagerule_targets),count.index)])}"
  // because priority in the web UI is ordered in the inverse compared to priority (the higher number in the UI, the lower priority)
  // we use the key value with a numbered convention
  //  * 10-19: defaults, lowest priority, more general settings
  //  * 30-79: special wildcards for URIs
  //  * 800+: special single URIs with peculiar settings
  // because the ordering is preserved when using lexicographica listing from the keys
  // we can use the index of the array
  priority = "${count.index + 1}"
}
```

What happens with this is the ordering does not change when applying, next time you will only have changes related to rules insertion/deletion

**Comment by vital4ik** [comment] 2020-01-03 18:34
the issue is still happening for us even on latest TF and CF provider versions. the workaround we have for now is to just run the apply on the page rules module multiple times with -parallelism=1, empricially we see that all collisions are resolved and we achieve correct order of the page rules after 4 runs on a set of 40 rules. does anyone know if cloudflare is planning to provide a fix for this issue?

**Comment by jacobbednarz** [comment] 2020-01-03 19:39
This isn’t something the provider can fix as mentioned earlier in this issue. You’ll need to use one of the workarounds in this thread. 

Cloudflare have mentioned this isn’t something they will be fixing as it is more likely they would replace the mechanism used instead. 

I’m going to lock this issue as nothing will change from the provider side however the workarounds should stay visible to others.

**Closed** 2020-03-22 23:38 UTC
Labels: bug, technical-debt, upstream
