### ISSUE TITLE
Feature Request: Support for managing worker scripts

### ISSUE THREAD

**Issue by derekargueta** [terraform-providers/terraform-provider-cloudflare#110] opened 2018-08-29 17:03 UTC
From [the documentation](https://www.terraform.io/docs/providers/cloudflare/index.html) it doesn't seem that Worker JS files can be managed via Terraform. It'd be awesome if uploading/deleting/managing worker code and routes could be done through Terraform.

Worker API documentation: https://api.cloudflare.com/#worker-script-properties

**Comment by patryk** [comment] 2018-08-31 15:46
Duplicate of #50. Closing.

**Closed by patryk** 2018-08-31 15:46 UTC
Labels: documentation, enhancement, new-resource
