### ISSUE TITLE
cloudflare_access_policy doesn't support github organization constraints

### ISSUE THREAD

**Issue by fd** [terraform-providers/terraform-provider-cloudflare#579] opened 2020-01-15 09:52 UTC
`cloudflare_access_policy` has no way of specifying a github organisation constraint for the `include` , `require` and `exclude`  blocks.

**Comment by jacobbednarz** [comment] 2020-01-15 10:13
Duplicate of #188

**Closed by jacobbednarz** 2020-01-15 10:13 UTC
