### ISSUE TITLE
Feature Request: cloudflare resource for access policy does not support cors feature

### ISSUE THREAD

**Issue by vital4ik** [terraform-providers/terraform-provider-cloudflare#624] opened 2020-03-17 14:02 UTC
Hi, we are a paying customer and trying to create a access policy resource and it looks like we cant control CORS settings via the provider. What are the plans to 

### Terraform Version
0.12.19
provider.cloudflare v2.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
cloudflare_access_policy

### Expected Behavior
config values to control cors behavior during the policy creation

### Actual Behavior
no option to setup controls for cors behavior for policy

**Comment by jacobbednarz** [comment] 2020-03-17 20:05
Duplicate of #473

**Closed** 2020-03-17 20:05 UTC
